---
name: execrcise-3
on: 
  push: 
    branches: 
      - dev

jobs: 
  learing: 
    runs-on: ubuntu-latest
    steps: 
      - name: ping test
        run: pin -c 4 google.com                              