---
name: rajesh
on: 
  push: 
    branches: 
      - main 

jobs: 
   learing: 
      runs-on: ubuntu-latest
      steps: 
          - name: learing
            run: "echo rajesh hello how are you"  
          - run: echo lucky how are you  

