---
name: exercise-1
on: 
  push: 
    branches: 
      - main
      
jobs: 
   learing: 
     runs-on: ubuntu-latest
     steps: 
        - name: learing
          run: "echo hello how are you"
        - run: echo hello are you
